"use client";

import { motion } from "motion/react";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";
import { ArrowLeft, Palette, Sparkles, Eye } from "lucide-react";

export default function About() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-transparent relative">
      <div className="home-container fixed inset-0 z-0 overflow-hidden" />

      <header className="relative z-10 p-6">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => router.back()}
          className="hover:bg-card/60"
        >
          <ArrowLeft size={18} />
        </Button>
      </header>

      <main className="relative z-10 max-w-4xl mx-auto px-6 pb-20">
        <div className="text-center mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="mb-8"
          >
            <h1 className="text-6xl md:text-7xl font-bold mb-6 tracking-tight">
              About <span className="brand-gradient-text">Helix</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Where AI meets beautiful design. Creating websites that look
              crafted by humans, not generated by machines.
            </p>
          </motion.div>
        </div>

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-16"
        >
          <div className="bg-card/60 supports-[backdrop-filter]:bg-card/70 border rounded-2xl p-8 backdrop-blur-md">
            <h2 className="text-3xl font-bold mb-6 text-center">
              The Problem We Solve
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed text-center max-w-3xl mx-auto">
              While other tools can generate functional websites, they often
              look obviously AI generated generic, sterile, and lacking
              personality. Helix bridges this gap by creating websites that are
              not just functional, but genuinely beautiful and engaging.
            </p>
          </div>
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold mb-8 text-center">
            What Makes Helix Different
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: <Palette className="w-8 h-8" />,
                title: "Beautiful by Design",
                description:
                  "Every generated website features thoughtful design, proper spacing, and visual hierarchy that feels human crafted.",
              },
              {
                icon: <Sparkles className="w-8 h-8" />,
                title: "Premium Aesthetics",
                description:
                  "Modern gradients, smooth animations, and polished components that rival the best human designed sites.",
              },
              {
                icon: <Eye className="w-8 h-8" />,
                title: "Visual Intelligence",
                description:
                  "Our AI understands design principles, not just code—creating websites you'd be proud to show clients.",
              },
            ].map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.3 + index * 0.1 }}
                className="bg-card/60 supports-[backdrop-filter]:bg-card/70 border rounded-2xl p-6 backdrop-blur-md hover:bg-card/80 transition-colors"
              >
                <div className="text-primary mb-4">{feature.icon}</div>
                <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                <p className="text-muted-foreground leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="mb-16"
        >
          <div className="bg-card/60 supports-[backdrop-filter]:bg-card/70 border rounded-2xl p-8 backdrop-blur-md">
            <h2 className="text-3xl font-bold mb-6 text-center">
              Why Beautiful Matters
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed text-center max-w-3xl mx-auto mb-8">
              In today&apos;s digital landscape, first impressions happen in
              milliseconds. A beautifully designed website builds trust, engages
              users, and converts better than its generic counterparts. Helix
              ensures your AI generated sites never scream &quot;template&quot;
              or &quot;auto generated&quot; they look intentionally crafted and
              professionally designed.
            </p>
            <div className="text-center">
              <div className="inline-flex items-center gap-4 text-sm text-muted-foreground">
                <span>Redefining what AI generated websites can look like</span>
              </div>
            </div>
          </div>
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.6 }}
          className="text-center"
        >
          <div className="bg-card/60 supports-[backdrop-filter]:bg-card/70 border rounded-2xl p-8 backdrop-blur-md">
            <h2 className="text-3xl font-bold mb-4">
              Experience the Difference
            </h2>
            <p className="text-muted-foreground mb-8 max-w-xl mx-auto">
              See why designers and developers choose Helix when they need
              websites that look professionally crafted, not AI generated.
            </p>
            <Button
              size="lg"
              onClick={() => router.push("/")}
              className="px-8 py-3 text-lg"
            >
              Create Beautiful Websites
            </Button>
          </div>
        </motion.section>
      </main>
    </div>
  );
}
